//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NinjaStore.UnitTest.OrderHistorySrvc {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Order", Namespace="http://schemas.datacontract.org/2004/07/NinjaStore.SOAP")]
    [System.SerializableAttribute()]
    public partial class Order : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private NinjaStore.UnitTest.OrderHistorySrvc.Customer CustomerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int OrderIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private NinjaStore.UnitTest.OrderHistorySrvc.Product ProductField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int QuantityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double TotalAmountField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public NinjaStore.UnitTest.OrderHistorySrvc.Customer Customer {
            get {
                return this.CustomerField;
            }
            set {
                if ((object.ReferenceEquals(this.CustomerField, value) != true)) {
                    this.CustomerField = value;
                    this.RaisePropertyChanged("Customer");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int OrderId {
            get {
                return this.OrderIdField;
            }
            set {
                if ((this.OrderIdField.Equals(value) != true)) {
                    this.OrderIdField = value;
                    this.RaisePropertyChanged("OrderId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public NinjaStore.UnitTest.OrderHistorySrvc.Product Product {
            get {
                return this.ProductField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductField, value) != true)) {
                    this.ProductField = value;
                    this.RaisePropertyChanged("Product");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Quantity {
            get {
                return this.QuantityField;
            }
            set {
                if ((this.QuantityField.Equals(value) != true)) {
                    this.QuantityField = value;
                    this.RaisePropertyChanged("Quantity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double TotalAmount {
            get {
                return this.TotalAmountField;
            }
            set {
                if ((this.TotalAmountField.Equals(value) != true)) {
                    this.TotalAmountField = value;
                    this.RaisePropertyChanged("TotalAmount");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Customer", Namespace="http://schemas.datacontract.org/2004/07/NinjaStore.SOAP")]
    [System.SerializableAttribute()]
    public partial class Customer : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CustomerIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CustomerLocationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CustomerNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CustomerID {
            get {
                return this.CustomerIDField;
            }
            set {
                if ((this.CustomerIDField.Equals(value) != true)) {
                    this.CustomerIDField = value;
                    this.RaisePropertyChanged("CustomerID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CustomerLocation {
            get {
                return this.CustomerLocationField;
            }
            set {
                if ((object.ReferenceEquals(this.CustomerLocationField, value) != true)) {
                    this.CustomerLocationField = value;
                    this.RaisePropertyChanged("CustomerLocation");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CustomerName {
            get {
                return this.CustomerNameField;
            }
            set {
                if ((object.ReferenceEquals(this.CustomerNameField, value) != true)) {
                    this.CustomerNameField = value;
                    this.RaisePropertyChanged("CustomerName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Product", Namespace="http://schemas.datacontract.org/2004/07/NinjaStore.SOAP")]
    [System.SerializableAttribute()]
    public partial class Product : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double PriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProductIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProductNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Price {
            get {
                return this.PriceField;
            }
            set {
                if ((this.PriceField.Equals(value) != true)) {
                    this.PriceField = value;
                    this.RaisePropertyChanged("Price");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProductId {
            get {
                return this.ProductIdField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductIdField, value) != true)) {
                    this.ProductIdField = value;
                    this.RaisePropertyChanged("ProductId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProductName {
            get {
                return this.ProductNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductNameField, value) != true)) {
                    this.ProductNameField = value;
                    this.RaisePropertyChanged("ProductName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="OrderHistorySrvc.IOrders")]
    public interface IOrders {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrders/GetAllOrders", ReplyAction="http://tempuri.org/IOrders/GetAllOrdersResponse")]
        NinjaStore.UnitTest.OrderHistorySrvc.Order[] GetAllOrders();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrders/GetAllOrders", ReplyAction="http://tempuri.org/IOrders/GetAllOrdersResponse")]
        System.Threading.Tasks.Task<NinjaStore.UnitTest.OrderHistorySrvc.Order[]> GetAllOrdersAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrders/GetOrderbyOrderID", ReplyAction="http://tempuri.org/IOrders/GetOrderbyOrderIDResponse")]
        NinjaStore.UnitTest.OrderHistorySrvc.Order GetOrderbyOrderID(int OrderId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrders/GetOrderbyOrderID", ReplyAction="http://tempuri.org/IOrders/GetOrderbyOrderIDResponse")]
        System.Threading.Tasks.Task<NinjaStore.UnitTest.OrderHistorySrvc.Order> GetOrderbyOrderIDAsync(int OrderId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrders/GetOrdersbyProductID", ReplyAction="http://tempuri.org/IOrders/GetOrdersbyProductIDResponse")]
        NinjaStore.UnitTest.OrderHistorySrvc.Order[] GetOrdersbyProductID(string ProductId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrders/GetOrdersbyProductID", ReplyAction="http://tempuri.org/IOrders/GetOrdersbyProductIDResponse")]
        System.Threading.Tasks.Task<NinjaStore.UnitTest.OrderHistorySrvc.Order[]> GetOrdersbyProductIDAsync(string ProductId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrders/GetOrdersbyCustomerID", ReplyAction="http://tempuri.org/IOrders/GetOrdersbyCustomerIDResponse")]
        NinjaStore.UnitTest.OrderHistorySrvc.Order[] GetOrdersbyCustomerID(int CustomersId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrders/GetOrdersbyCustomerID", ReplyAction="http://tempuri.org/IOrders/GetOrdersbyCustomerIDResponse")]
        System.Threading.Tasks.Task<NinjaStore.UnitTest.OrderHistorySrvc.Order[]> GetOrdersbyCustomerIDAsync(int CustomersId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IOrdersChannel : NinjaStore.UnitTest.OrderHistorySrvc.IOrders, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class OrdersClient : System.ServiceModel.ClientBase<NinjaStore.UnitTest.OrderHistorySrvc.IOrders>, NinjaStore.UnitTest.OrderHistorySrvc.IOrders {
        
        public OrdersClient() {
        }
        
        public OrdersClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public OrdersClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OrdersClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OrdersClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public NinjaStore.UnitTest.OrderHistorySrvc.Order[] GetAllOrders() {
            return base.Channel.GetAllOrders();
        }
        
        public System.Threading.Tasks.Task<NinjaStore.UnitTest.OrderHistorySrvc.Order[]> GetAllOrdersAsync() {
            return base.Channel.GetAllOrdersAsync();
        }
        
        public NinjaStore.UnitTest.OrderHistorySrvc.Order GetOrderbyOrderID(int OrderId) {
            return base.Channel.GetOrderbyOrderID(OrderId);
        }
        
        public System.Threading.Tasks.Task<NinjaStore.UnitTest.OrderHistorySrvc.Order> GetOrderbyOrderIDAsync(int OrderId) {
            return base.Channel.GetOrderbyOrderIDAsync(OrderId);
        }
        
        public NinjaStore.UnitTest.OrderHistorySrvc.Order[] GetOrdersbyProductID(string ProductId) {
            return base.Channel.GetOrdersbyProductID(ProductId);
        }
        
        public System.Threading.Tasks.Task<NinjaStore.UnitTest.OrderHistorySrvc.Order[]> GetOrdersbyProductIDAsync(string ProductId) {
            return base.Channel.GetOrdersbyProductIDAsync(ProductId);
        }
        
        public NinjaStore.UnitTest.OrderHistorySrvc.Order[] GetOrdersbyCustomerID(int CustomersId) {
            return base.Channel.GetOrdersbyCustomerID(CustomersId);
        }
        
        public System.Threading.Tasks.Task<NinjaStore.UnitTest.OrderHistorySrvc.Order[]> GetOrdersbyCustomerIDAsync(int CustomersId) {
            return base.Channel.GetOrdersbyCustomerIDAsync(CustomersId);
        }
    }
}
